# basic settings
task_name: object_counting # bigbench | ncbi | ... | or your own task
search_algo: beam_search # mcts | beam_search
print_log: true
log_dir: ./logs/

# your initial prompt
#init_prompt: |
#  Answer questions about a table of penguins and their attributes.
init_prompt: |
  Questions that involve enumerating objects of different types and asking the model to count them

task_setting:
  train_size: 700
  eval_size: 150 # data split for reward calculation
  test_size: 150 # if test_size is not 0, the optimized nodes will be tested at last.
  seed: 42 # if need to fixed shuffled dataset
  data_dir: E:/2025/model/lunwen/APE/datasets/object_counting.json # if data is downloaded
  # Note: the current supported bigbench tasks are specified by 
  # data_dir using the same task_name (bigbench), if there is not
  # specific .py class inplemented in the tasks folder.
  post_instruction: false # false: prompt + task question | true: task question + prompt

base_model_setting:
  model_type: openai # openai | palm | hf_text2text | hf_textgeneration | ct_model
#  model_name: deepseek-r1 # api-based model'name or huggingface model name
  model_name: gpt-4o-mini
#  model_name: o1-mini
  temperature: 0.0
  api_key: sk-iQgw71x5JsUTG93Ya4LlGBL7HLY3GJuTX8negxcmfDi2LLAW # if need api key
  device: cuda:0 # cuda | cpu | cuda:x, e.g. 0,1,2...
  gpu_ids: [0] # [0,1,...] for vllm model
  model_path: null # ct model requires the downloaded model's path

optim_model_setting:
  model_type: openai # openai | palm | hf_text2text | hf_textgeneration | ct_model
#  model_name: deepseek-reasoner # api-based model'name or huggingface model name
  model_name: gpt-4o-mini
  temperature: 1.0
  api_key: sk-iQgw71x5JsUTG93Ya4LlGBL7HLY3GJuTX8negxcmfDi2LLAW  # if need api key
  device: cuda:0 # cuda | cpu | cuda:x, e.g. 0,1,2...
  gpu_ids: 0 # [0,1,...] for vllm model
  model_path: null # ct model requires the downloaded model's path

search_setting:
  iteration_num: 10
  expand_width: 3 # num of branches of each node
  depth_limit: 5 # the max depth of mcts
  # mcts setting
  min_depth: 2 # min depth of mcts for early stop
  w_exp: 2.5 # balance exploration and exploitation
  # beam search setting
  beam_width: 3

world_model_setting:
  # mcts world model setting
  train_shuffle: true
#  num_new_prompts: 1 # 3 if beam search
  num_new_prompts: 3
  train_batch_size: 5
  
